import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function TopNav() {
  return (
    <nav className="flex w-full m-auto items-center justify-between text-xs font-semibold px-5 py-2">
      <div className="flex items-start gap-5">
        <Link href="/">primapress</Link>
        <Link href="/about">Info</Link>
      </div>
      <div className="flex items-end gap-5">
        <Link href="/">Instagram</Link>
        <Link href="/catalog">Catálogo</Link>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNav />
        {children}
      </body>
    </html>
  );
}
